# Generated by Django 4.0.1 on 2022-02-02 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfundamentals',
            name='div',
        ),
        migrations.RemoveField(
            model_name='companyfundamentals',
            name='volume',
        ),
    ]
