# Generated by Django 4.0.1 on 2022-02-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_remove_companyfundamentals_div_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfundamentals',
            name='div',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='companyfundamentals',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
