# Generated by Django 4.0.1 on 2022-02-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0006_companyfundamentals_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfundamentals',
            name='url',
        ),
    ]
